name: Download MNIST Dataset

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  download-dataset:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check if dataset exists
      run: |
        if [ -f "data/mnist_raw.npz" ]; then
          echo "Dataset already exists. Skipping download."
          exit 0
        fi
    
    - name: Download MNIST dataset
      run: python src/download_dataset.py
    
    - name: Commit dataset to repository
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/paezdev/paez_jean_MNIST.git
        git add data/mnist_raw.npz
        git commit -m "Add MNIST dataset"
        git push